# Settings for your local setup
local_mac:
  must_exists: /Volumes/data/repo/
  bert_dir: /Volumes/data/repo/data/bert
  datasets_dir: /Volumes/data/repo/data
  workers: 4

# Settings for your GPU server
gpu_server:
  must_exists: /usr/bin/nvidia-smi
  bert_dir: /mnt/hdd/datasets/BERT_pre_trained_models/pytorch
  datasets_dir: /mnt/hdd/datasets
  workers: 12